# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ReactNativeStarter' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'ReactNativeStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_native_modules!
end

target 'ReactNativeStarter-tvOS' do
  target 'ReactNativeStarter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
